# Generated by Django 4.2 on 2023-05-13 23:24

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0005_remove_event_attendees_alter_event_organizer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='poster',
        ),
        migrations.AddField(
            model_name='event',
            name='attendees',
            field=models.ManyToManyField(null=True, related_name='registered_event', through='events.Registration', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='cover',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='uploads/% Y/% m/% d/'),
            preserve_default=False,
        ),
    ]
